### ISSUE TITLE
Uncaught SyntaxError: Unexpected token R

### ISSUE THREAD

**Issue by phyllisstein** [Jacob84/rspec-tree-runner#1]
Hey there! I love the idea for this package and was eager to give it a shot, but I ran into a little glitch in the results-parsing logic. It currently appears to be calling `JSON.parse` on the raw console output, which in my case looks like this:

```
Randomized with seed 57186


Progress: |====================================================================|

Finished in 0.18815 seconds (files took 0.53816 seconds to load)
1 example, 0 failures

Randomized with seed 57186
```

...and since that's no kind of JSON, it's choking and crashing. So far I'm not quite sure what would be more helpful there, or else I'd just submit a pull request---are you counting on the user to have a particular RSpec formatter installed that'd output JSON, or were you looking for another method on the JavaScript side? Happy to help in any way I can, if you can help me get a sense of what you were going for.

Thanks for giving this a shot! Looks like it'll be a great tool once this gets ironed out.

---

**Atom Version**: 0.199.0
**System**: Mac OS X 10.10.4
**Thrown From**: [rspec-tree-runner](https://github.com/jacobmendoza/rspec-tree-runner) package, v0.1.0
### Stack Trace

Uncaught SyntaxError: Unexpected token R

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3Anull%7D%5D%2C%22bootstrapScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22apiPreviewMode%22%3Afalse%2C%22appVersion%22%3A%220.199.0%22%2C%22initialPaths%22%3A%5B%22%2FUsers%2Fdanielsh%2FRepos%2FIgnota%2FRupertsberg%22%5D%7D:2

SyntaxError: Unexpected token R
  at Object.parse (native)
  at RSpecLauncherCommand.module.exports.RSpecLauncherCommand.parseRSpecResult (/Users/danielsh/.atom/packages/rspec-tree-runner/lib/rspec-launcher-command.coffee:25:57)
  at /Users/danielsh/.atom/packages/rspec-tree-runner/lib/rspec-launcher-command.coffee:17:54
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TerminalCommandRunner.module.exports.TerminalCommandRunner.onClose (/Users/danielsh/.atom/packages/rspec-tree-runner/lib/terminal-command-runner.coffee:47:14)
  at ChildProcess.<anonymous> (/Users/danielsh/.atom/packages/rspec-tree-runner/lib/terminal-command-runner.coffee:1:1)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at maybeClose (child_process.js:997:16)
  at Socket.<anonymous> (child_process.js:1166:11)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```
### Commands

```
     -6:14.5.0 project-manager:toggle (atom-pane.pane.active)
     -6:13 core:confirm (atom-text-editor.editor.mini.is-focused)
     -6:08.6.0 rspec-tree-runner:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -5:55 rspec-tree-runner:toggle-spec-file (atom-text-editor.editor.is-focused)
     -5:52.4.0 pane:show-previous-item (atom-text-editor.editor.is-focused)
     -5:50.5.0 rspec-tree-runner:run-tests (atom-text-editor.editor.is-focused)
     -5:38.8.0 core:move-up (atom-text-editor.editor.is-focused)
     -5:38.3.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -5:38.1.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -5:37.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:36.4.0 core:move-to-bottom (atom-text-editor.editor.is-focused)
     -5:32.2.0 core:save (atom-text-editor.editor.is-focused)
     -2:29.2.0 rspec-tree-runner:run-tests (atom-text-editor.editor.is-focused)
  2x -0:56 settings-view:open (atom-text-editor.editor.is-focused)
     -0:30.2.0 editor:move-to-first-character-of-line (atom-text-editor#rspec-tree-runner.rspecPathCommand.editor.mini.is-focused)
     -0:22.1.0 rspec-tree-runner:run-tests (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "followSymlinks": true,
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "Thumbs.db",
      ".bundle",
      ".capistrano",
      "log",
      "tmp",
      "bower_components",
      "node_modules",
      ".keep",
      ".latex",
      "bin"
    ],
    "projectHome": "/Users/danielsh/Repos",
    "disabledPackages": [
      "wrap-guide",
      "deprecation-cop",
      "keybinding-resolver",
      "autocomplete",
      "background-tips",
      "remote-atom",
      "markdown-preview-pandoc",
      "autocomplete-css",
      "autocomplete-html",
      "autocomplete-plus",
      "autocomplete-snippets",
      "autocomplete-atom-api"
    ],
    "excludeVcsIgnoredPaths": false,
    "audioBeep": false
  },
  "rspec-tree-runner": {
    "rspecPathCommand": "bin/rspec",
    "rubyPathCommand": "/usr/local/bin/ruby"
  }
}
```
### Installed Packages

``` coffee
# User
Stylus, v1.0.0
aligner-ruby, v1.4.0
api-blueprint-preview, v0.3.0
atom-beautify, v0.27.1
atomatigit, v1.3.0
build, v0.32.0
caniuse, v0.5.3
compare-files, v0.4.1
docblockr, v0.7.1
ease-blink, v0.5.1
figlet, v0.4.0
file-icons, v1.5.5
file-types, v0.3.0
foldingtext-for-atom, v0.1.4
foldingtext-markdown, v1.2.2
git-tab-status, v1.9.2
highlight-selected, v0.9.3
hipster-ipsum, v0.1.0
http-status-codes, v1.0.3
keybinding-cheatsheet, v0.0.9
language-api-blueprint, v1.0.1
language-jade, v0.4.0
language-latex, v0.6.1
language-nginx, v0.5.2
language-rspec, v0.3.0
latex, v0.23.4
less-than-slash, v0.6.0
markdown-table-formatter, v2.5.2
minimap, v4.8.0
minimap-color-highlight, v4.1.3
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.3
minimap-selection, v4.2.0
one-dark-syntax, v0.5.0
one-dark-ui, v0.8.1
pain-split, v1.4.0
pdf-view, v0.22.0
pigments, v0.2.1
project-manager, v1.15.5
quick-move-file, v0.7.0
remote-edit, v1.7.2
resize-indent, v0.2.1
rspec-tree-runner, v0.1.0
slim-language, v2.2.0
svg-preview, v0.5.1
tasks, v2.0.1
untitled-no-more, v0.1.0
wakatime, v4.0.9
web-browser, v1.4.4
wordcount, v2.2.2

# Dev
No dev packages
```

**Comment by phyllisstein** [comment]
D'oh, Googled "RSpec JSON formatter" _immediately_ after posting that and found the built-in one. Oh well---I can at least update the README!
