### ISSUE TITLE
Uncaught SyntaxError: Unexpected token Y

### ISSUE THREAD

**Issue by alaibe** [Jacob84/rspec-tree-runner#10]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.4
**System**: Mac OS X 10.10.4
**Thrown From**: [rspec-tree-runner](https://github.com/jacobmendoza/rspec-tree-runner) package, v0.1.2
### Stack Trace

Uncaught SyntaxError: Unexpected token Y

```
At file:///Users/anthony/Downloads/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%7D%5D%2C%22bootstrapScript%22%3A%22%2FUsers%2Fanthony%2FDownloads%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2FUsers%2Fanthony%2FDownloads%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22profileStartup%22%3Afalse%2C%22appVersion%22%3A%221.0.4%22%2C%22shellLoadTime%22%3A302%2C%22initialPaths%22%3A%5B%22%2FUsers%2Fanthony%2Fapps%2Fsp%2Fsmartpension%22%5D%7D:1

SyntaxError: Unexpected token Y
  at Object.parse (native)
  at RSpecLauncherCommand.module.exports.RSpecLauncherCommand.parseRSpecResult (/Users/anthony/.atom/packages/rspec-tree-runner/lib/rspec-launcher-command.coffee:25:57)
  at /Users/anthony/.atom/packages/rspec-tree-runner/lib/rspec-launcher-command.coffee:17:54
  at Emitter.module.exports.Emitter.emit (/Users/anthony/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TerminalCommandRunner.module.exports.TerminalCommandRunner.onClose (/Users/anthony/.atom/packages/rspec-tree-runner/lib/terminal-command-runner.coffee:47:14)
  at ChildProcess.<anonymous> (/Users/anthony/.atom/packages/rspec-tree-runner/lib/terminal-command-runner.coffee:1:1)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at maybeClose (child_process.js:997:16)
  at Socket.<anonymous> (child_process.js:1166:11)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```
### Commands

```
     -3:40.4.0 settings-view:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  7x -3:33.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:25.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:29.6.0 rspec-tree-runner:toggle (div.settings-view.pane-item)
     -1:18.8.0 rspec-tree-runner:run-tests (atom-text-editor.editor.is-focused)
  2x -1:13.3.0 rspec-tree-runner:toggle-spec-file (atom-text-editor.editor.is-focused)
  2x -1:06.2.0 core:close (atom-text-editor.editor.is-focused)
     -1:00.0 rspec-tree-runner:run-tests (atom-text-editor.editor.is-focused)
     -0:57 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
  2x -0:52 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:51.3.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:50.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:37.8.0 rspec-tree-runner:run-tests (atom-text-editor.editor.is-focused)
  4x -0:16.4.0 core:backspace (atom-text-editor#rspec-tree-runner.rspecPathCommand.editor.mini.is-focused)
     -0:08.4.0 core:save (atom-text-editor#rspec-tree-runner.rspecPathCommand.editor.mini.is-focused)
     -0:02.9.0 rspec-tree-runner:run-tests (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "rspec-tree-runner": {
    "rspecPathCommand": "bundle exec rspec"
  }
}
```
### Installed Packages

``` coffee
# User
circle-ci, v0.10.0
irc, v0.4.0
language-slim, v0.5.0
rspec-tree-runner, v0.1.2

# Dev
No dev packages
```

**Comment by jacobmendoza** [comment]
Hi @alaibe,

Thanks a lot for your feedback. Sorry that it took so long.

I've discovered a problem when getting the result of the tests, sometimes they contain unescaped characters. Just released a new version that could fix that.

I would really appreciate if you can download it.

If you don't mind, I will close this one now. You can comment more on #4 or reopen if you think your issue is different.
