### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by thibaudgg** [Jacob84/rspec-tree-runner#11]
Just tried to run normal model spec.

**Atom Version**: 1.0.5
**System**: Mac OS X 10.10.4
**Thrown From**: [rspec-tree-runner](https://github.com/jacobmendoza/rspec-tree-runner) package, v0.1.2
### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/Thibaud/.atom/packages/rspec-tree-runner/lib/tree-builder.coffee:19

TypeError: Cannot read property 'length' of undefined
  at TreeBuilder.module.exports.TreeBuilder.updateWithTests (/Users/Thibaud/.atom/packages/rspec-tree-runner/lib/tree-builder.coffee:19:68)
  at PluginState.module.exports.PluginState.updateTreeWithTests (/Users/Thibaud/.atom/packages/rspec-tree-runner/lib/plugin-state.coffee:83:27)
  at /Users/Thibaud/.atom/packages/rspec-tree-runner/lib/plugin-state.coffee:60:10
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at RSpecLauncherCommand.module.exports.RSpecLauncherCommand.parseRSpecResult (/Users/Thibaud/.atom/packages/rspec-tree-runner/lib/rspec-launcher-command.coffee:26:14)
  at /Users/Thibaud/.atom/packages/rspec-tree-runner/lib/rspec-launcher-command.coffee:17:54
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TerminalCommandRunner.module.exports.TerminalCommandRunner.onClose (/Users/Thibaud/.atom/packages/rspec-tree-runner/lib/terminal-command-runner.coffee:47:14)
  at ChildProcess.<anonymous> (/Users/Thibaud/.atom/packages/rspec-tree-runner/lib/terminal-command-runner.coffee:1:1)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at maybeClose (child_process.js:997:16)
  at Socket.<anonymous> (child_process.js:1166:11)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```
### Commands

```
     -6:43.1.0 rspec-tree-runner:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -6:31.5.0 rspec-tree-runner:run-tests (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -6:11.4.0 settings-view:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -6:03.1.0 tree-view:toggle (atom-text-editor.editor.mini.is-focused)
     -5:46.3.0 core:backspace (atom-text-editor#rspec-tree-runner.rspecPathCommand.editor.mini.is-focused)
     -5:33.6.0 core:copy (atom-text-editor#rspec-tree-runner.rspecPathCommand.editor.mini.is-focused)
     -5:18.4.0 core:save (atom-text-editor#rspec-tree-runner.rspecPathCommand.editor.mini.is-focused)
  2x -5:18 core:close (atom-text-editor#rspec-tree-runner.rspecPathCommand.editor.mini.is-focused)
     -0:49 rspec-tree-runner:run-tests (atom-text-editor.editor.is-focused)
     -0:31.6.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:31.6.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:28.9.0 tree-view:toggle (atom-text-editor.editor.is-focused)
     -0:25.4.0 settings-view:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:09.4.0 core:confirm (atom-text-editor#rspec-tree-runner.sizeOfRSpecMessageStrings.editor.mini.is-focused)
     -0:06.6.0 core:close (atom-text-editor#rspec-tree-runner.sizeOfRSpecMessageStrings.editor.mini.is-focused)
     -0:03.7.0 rspec-tree-runner:run-tests (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "projectHome": "/Users/Thibaud/Codes",
    "ignoredNames": [
      ".git",
      "tmp",
      "log",
      "coverage"
    ],
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "atom-dark-ui",
      "railscasts-syntax"
    ],
    "disabledPackages": [
      "tree-view-git-modified"
    ]
  },
  "rspec-tree-runner": {
    "rspecPathCommand": "./bin/rspec"
  }
}
```
### Installed Packages

``` coffee
# User
circle-ci, v0.10.0
highlight-selected, v0.10.1
language-rspec, v0.3.0
linter, v1.3.4
linter-reek, v2.0.0
linter-rubocop, v0.3.1
linter-ruby, v1.0.1
railscasts-syntax, v0.4.0
rspec-snippets, v0.4.0
rspec-tree-runner, v0.1.2
ruby-slim, v0.2.0
ruby-test, v0.9.11
tree-view-open-files, v0.2.4

# Dev
No dev packages
```

**Comment by rngtng** [comment]
I got the same. It happens when output of rspec-analyser couldn't be parsed. Can you post the rspec file you wanted to execute?

**Comment by jacobmendoza** [comment]
Hi @thibaudgg,

Thanks a lot for the feedback!. As @rngtng was saying, it has to be related with the parsing of the output of RSpec. Some unexpected error is happening. 

I'm not sure if it is related to #4, as the output is different. The first step should be update to the new version released yesterday, that fixes the output when some characters are unescaped. That could be one of the reasons.

The package does two things when running a test file (ctrl+alt+x or ctrl+alt+r), changing to the project directory and then running RSpec to get the results (in JSON format). Please, can you run RSpec inside your project and post here the relevant part of the result?. Should be similar to:

Open a terminal
cd project_directoy
rspec --format=json spec/file_that_failed_spec.rb

Thank you!

**Comment by thibaudgg** [comment]
Hey @jacobmendoza 

`rspec --format=json spec/file_that_failed_spec.rb` works fine but I still get the same issue with 0.2.0.

I also noticed that "ctrl+alt+r" is not running a single test but is doing the same as "ctrl-alt-q" (toggle spec files).

**Comment by jacobmendoza** [comment]
Hey @thibaudgg.

It's really strange that behaviour that you're reporting from the ctrl+alt+r. I'm trying to reproduce.

Also, it would help a lot if you can paste the output of the rspec --format=json. It should be something in the output that the package isn't able to process.

Thank you! :).

**Comment by thibaudgg** [comment]
Sure, please see the output of a falling spec:

```
rspec --format=json spec/models/user_spec.rb:10
{"version":"3.3.2","messages":["Run options: include {:focus=>true, :locations=>{\"./spec/models/user_spec.rb\"=>[10]}}"],"examples":[{"description":"accepts user without gender and year_of_birth","full_description":"User validations accepts user without gender and year_of_birth","status":"failed","file_path":"./spec/models/user_spec.rb","line_number":8,"run_time":0.545614,"pending_message":null,"exception":{"class":"RSpec::Expectations::ExpectationNotMetError","message":"expected #count not to have changed, but did change from 0 to 1","backtrace":["/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-support-3.3.0/lib/rspec/support.rb:86:in `block in <module:Support>'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-support-3.3.0/lib/rspec/support.rb:93:in `call'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-support-3.3.0/lib/rspec/support.rb:93:in `notify_failure'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-expectations-3.3.1/lib/rspec/expectations/fail_with.rb:27:in `fail_with'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-expectations-3.3.1/lib/rspec/expectations/handler.rb:40:in `handle_failure'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-expectations-3.3.1/lib/rspec/expectations/handler.rb:72:in `block in handle_matcher'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-expectations-3.3.1/lib/rspec/expectations/handler.rb:27:in `with_matcher'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-expectations-3.3.1/lib/rspec/expectations/handler.rb:70:in `handle_matcher'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-expectations-3.3.1/lib/rspec/expectations/expectation_target.rb:67:in `not_to'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-expectations-3.3.1/lib/rspec/expectations/expectation_target.rb:92:in `not_to'","/Users/Thibaud/Codes/Foo/spec/models/user_spec.rb:9:in `block (3 levels) in <top (required)>'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:206:in `instance_exec'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:206:in `block in run'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:430:in `block in with_around_and_singleton_context_hooks'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:388:in `block in with_around_example_hooks'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:478:in `block in run'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:618:in `block in run_around_example_hooks_for'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:273:in `call'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:273:in `call'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-rails-3.3.3/lib/rspec/rails/adapters.rb:127:in `block (2 levels) in <module:MinitestLifecycleAdapter>'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:378:in `instance_exec'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:378:in `instance_exec'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:389:in `execute_with'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:620:in `block (2 levels) in run_around_example_hooks_for'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:273:in `call'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:273:in `call'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:621:in `run_around_example_hooks_for'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:478:in `run'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:388:in `with_around_example_hooks'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:430:in `with_around_and_singleton_context_hooks'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:203:in `run'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:559:in `block in run_examples'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:555:in `map'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:555:in `run_examples'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:521:in `run'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:522:in `block in run'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:522:in `map'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:522:in `run'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `block (3 levels) in run_specs'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `map'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `block (2 levels) in run_specs'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1627:in `with_suite_hooks'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:114:in `block in run_specs'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/reporter.rb:77:in `report'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:113:in `run_specs'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:89:in `run'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in `invoke'","/Users/Thibaud/.gem/ruby/2.2.3/gems/rspec-core-3.3.2/exe/rspec:4:in `<top (required)>'","/Users/Thibaud/.gem/ruby/2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'","/Users/Thibaud/.gem/ruby/2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'","/Users/Thibaud/.gem/ruby/2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'","/Users/Thibaud/.gem/ruby/2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'","/Users/Thibaud/.gem/ruby/2.2.3/gems/spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:18:in `call'","/Users/Thibaud/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'","/Users/Thibaud/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'","-e:1:in `<main>'"]}}],"summary":{"duration":0.590524,"example_count":1,"failure_count":1,"pending_count":0},"summary_line":"1 example, 1 failure"}
```

**Comment by jacobmendoza** [comment]
Hey @thibaudgg,

Thanks a lot for sharing your output. I thought that the error was related somehow with the parsing, but this part seems to be fine. It's here:

https://github.com/jacobmendoza/rspec-tree-runner/blob/master/lib/tree-builder.coffee#L19

It seems that the error is related with the initial building of the tree. The variable asTree is undefined and it should be defined, as the tree has been formed before trying to run any test (the tree comes from the parsing of the RSpec file). I have been trying to reproduce, but without luck.

Is the code a test project?. Is something OSS?. Could you prepare a small set of files that I could use to reproduce the error?.

I know it is a lot to ask. Just in case you have time. 

Thank you!

**Comment by thibaudgg** [comment]
Sadly I can't share the project, I don't think the issue is really related to a specific spec, maybe our spec_helper.rb? What are your guesses?

**Comment by jacobmendoza** [comment]
Hi @thibaudgg,

Your help is priceless. I'm a bit lost, and I don't have now all the time that I'd like to have to chase the bug. If you have time, I would like to confirm something with you. I think that the error is happening in the parsing of the RSpec file and not in the parsing of the results (which has been the most likely issue). It's the most complex part, and I don't have a lot of experience with Ruby, so it could be easily the problem.

So, if we focus on the RSpec file, can you create a new model with a new spec file and see if the error is happening?. If it is not happening with the new file, could you incrementally make the spec file more similar to the one that is failing.

I know that it could be a lot work, so just if you have time. Maybe I'm missing something very obvious.

Thanks a million.

**Comment by brand-it** [comment]
@jacobmendoza Looks like this error has prevented me from testing out #4 issue.

**Comment by brand-it** [comment]
Oh also I am at version `1.5.3` of atom if that helps at all.

**Comment by jacobmendoza** [comment]
Sorry to hear that @newdark. 

If you are experiencing exactly the same error as @thibaudgg, could be related with the RSpec file that you are trying to parse. I have never been able to debug this one. I was wondering, is this spec file something that you could share? (that specific one or other that reproduces the problem).

It would be great to have an example that fails to see if I can debug the script. Also, the specific stack trace that Atom gives you would be interesting, just to verify that we are observing the error in the same place.

Thanks for your help!

**Comment by jacobmendoza** [comment]
Hey @thibaudgg, @rngtng!

I've released a new version. The code has changed quite a lot, I would love to hear your feedback if you have the time.

Appreciated all your help. Closing this issue as probably it does not apply anymore.

**Comment by cheesepaulo** [comment]
I have the same issue / 1.0.4

**Comment by exocode** [comment]
hm... seems still not working... 

```
Uncaught TypeError: Cannot read property 'length' of undefined
/Users/janjezek/.atom/packages/rspec-tree-runner/lib/tree-builder.js:24
Hide Stack Trace
TypeError: Cannot read property 'length' of undefined
    at TreeBuilder.updateWithTests (/Users/janjezek/.atom/packages/rspec-tree-runner/lib/tree-builder.js:24:71)
    at PluginStateStore._updateTreeWithTests (/Users/janjezek/.atom/packages/rspec-tree-runner/lib/plugin-state-store.js:104:35)
    at RSpecLauncherCommand.<anonymous> (/Users/janjezek/.atom/packages/rspec-tree-runner/lib/plugin-state-store.js:157:9)
    at emitOne (events.js:116:13)
    at RSpecLauncherCommand.emit (events.js:211:7)
    at RSpecLauncherCommand.parseRSpecResult (/Users/janjezek/.atom/packages/rspec-tree-runner/lib/rspec-launcher-command.js:49:8)
    at TerminalCommandRunner.<anonymous> (/Users/janjezek/.atom/packages/rspec-tree-runner/lib/rspec-launcher-command.js:22:60)
    at emitOne (events.js:116:13)
    at TerminalCommandRunner.emit (events.js:211:7)
    at TerminalCommandRunner.onClose (/Users/janjezek/.atom/packages/rspec-tree-runner/lib/terminal-command-runner.js:38:8)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

**Comment by exocode** [comment]
Also when I open the "console" of Atom I can see this 

```
<embedded>:11 'rspec-tree-runner.rspecAnalyzerScript' could not set the default. Attempted default: undefined; Schema: {"type":"string"}

setDefaults @ <embedded>:11
transact @ <embedded>:11
transact @ <embedded>:11
setDefaults @ <embedded>:11
transact @ <embedded>:11
transact @ <embedded>:11
setSchema @ <embedded>:11
registerConfigSchemaFromMainModule @ <embedded>:11
activateConfig @ <embedded>:11
t.exports.PackageManager.packageHasSettings @ <embedded>:11
hasSettings @ <embedded>:14
updateSettingsState @ <embedded>:14
updateInterfaceState @ <embedded>:14
PackageCard @ <embedded>:14
createPackageCard @ <embedded>:14
addView @ <embedded>:14
ListView.list.onDidAddItem.e @ <embedded>:14
simpleDispatch @ <embedded>:11
emit @ <embedded>:11
setItems @ <embedded>:14
(anonymous) @ <embedded>:14
Promise resolved (async)
loadPackages @ <embedded>:14
InstalledPackagesPanel @ <embedded>:14
(anonymous) @ <embedded>:11
getOrCreatePanel @ <embedded>:11
showPanel @ <embedded>:11
clickHandler @ <embedded>:11
```

Maybe this will help

**Comment by exocode** [comment]
I scaffolded a simple rails 5.2.1 app with rspec installed and scaffold a user.
I kept some failed specs `......F*.F..**.............`
Using most recent Atom as well as latest `rspec-tree-runner`.
You can clone it here:
`git clone git@github.com:exocode/rspec-tester.git`
`cd rspec-tester`
`bundle install`
`rails db:setup`
`rake` or  `rspec` or with json format `rspec --format json`

I hope that this will be fixed soon, because I wanna leave `Rubymine`:-) And this feature will be a gamechanger.

Thank you very much in advance.


(I also tried to start debugging, but I am not familiar with Atom packages, and a "how to debug packages" Tutorial was not published right now.)
