### ISSUE TITLE
Uncaught SyntaxError: Unexpected token 

### ISSUE THREAD

**Issue by abscondite** [Jacob84/rspec-tree-runner#16]
edit command to 'bundle exec rspec'
run tests

**Atom Version**: 1.4.1
**System**: Mac OS X 10.11.2
**Thrown From**: [rspec-tree-runner](https://github.com/jacobmendoza/rspec-tree-runner) package, v0.2.0
### Stack Trace

Uncaught SyntaxError: Unexpected token 

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2FUsers%2Fmishke%2Fdev%project-backend%22%2C%22initialLine%22%3Anull%2C%22initialColumn%22%3Anull%7D%5D%2C%22windowInitializationScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Finitialize-application-window.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%221.4.1%22%2C%22atomHome%22%3A%22%2FUsers%2Fmishke%2F.atom%22%2C%22initialPaths%22%3A%5B%22%2FUsers%2Fmishke%2Fdev%project-backend%22%5D%7D:1

SyntaxError: Unexpected token 
    at Object.parse (native)
    at RSpecLauncherCommand.module.exports.RSpecLauncherCommand.parseRSpecResult (/Users/mishke/.atom/packages/rspec-tree-runner/lib/rspec-launcher-command.coffee:32:23)
    at /Users/mishke/.atom/packages/rspec-tree-runner/lib/rspec-launcher-command.coffee:22:54
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TerminalCommandRunner.module.exports.TerminalCommandRunner.onClose (/Users/mishke/.atom/packages/rspec-tree-runner/lib/terminal-command-runner.coffee:47:14)
    at ChildProcess.<anonymous> (/Users/mishke/.atom/packages/rspec-tree-runner/lib/terminal-command-runner.coffee:1:1)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Commands

```
     -3:26.6.0 core:move-left (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -3:26.1.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -3:25.7.0 core:save (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -3:20.2.0 rspec-tree-runner:toggle-spec-file (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  3x -3:17.4.0 rspec-tree-runner:run-tests (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -2:53.2.0 rspec-tree-runner:run-single-test (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -2:28.8.0 rspec-tree-runner:run-tests (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -2:24.9.0 core:copy (atom-notification.error.icon.icon-flame.native-key-bindings.has-detail)
     -1:58.4.0 terminal-panel:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:56.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:54.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:54.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  2x -1:24.7.0 rspec-tree-runner:run-tests (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:05.6.0 settings-view:open (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:20.9.0 rspec-tree-runner:toggle-spec-file (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:19 rspec-tree-runner:run-tests (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter-rubocop",
      "terminal-plus"
    ]
  },
  "rspec-tree-runner": {
    "rspecPathCommand": "bundle exec rspec"
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-ruby, v0.1.0
bottom-dock, v0.3.7
color-tabs, v0.1.8
file-icons, v1.6.14
language-rspec, v0.3.0
language-rspec-plus, v0.1.1
language-spec, v0.1.0
linter, v1.11.3
minimap, v4.19.0
minimap-git-diff, v4.1.8
pigments, v0.22.0
relative-numbers, v0.4.1
rspec-snippets, v0.4.0
rspec-tree-runner, v0.2.0
rspec3-snippets, v0.7.0
ruby-test-switcher, v1.2.0
slim-language, v2.2.0
terminal-panel, v1.14.1
todo-manager, v0.2.6
vim-mode, v0.64.0

# Dev
No dev packages
```

**Comment by jacobmendoza** [comment]
Hey @abscondite,

First of all, thanks for contacting me and reporting the error. This error has been usually happening when something not expected is being returned in the output for the RSpec test runner, which should be in json. One of the cases that we have seen, is using simplecov, that also returns the output when the formatter is json making the output invalid. 

If you have time and it's possible, I would love to see the output of rspec, to see if there is anything strange that is causing this behaviour. Should be similar to:

Open a terminal
cd project_directoy
rspec --format=json spec/file_that_failed_spec.rb

That way, I could inspect the output and see if there is something strange with that. In theory, it should allow me to reproduce the issue.

Thank you!

**Comment by jacobmendoza** [comment]
Hey @abscondite!,

I have released an update for the package that is supposed to fix this issue. Please, give it a go whenever you have time and let me know how it goes. I close this issue, but do not hesitate to reopen if it is still failing. 

Thanks for reporting again!.

**Comment by abscondite** [comment]
It works! Perfect. Thanks @jacobmendoza

**Comment by jacobmendoza** [comment]
Thank you so much!

Please, do not hesitate to give any feedback that you may have!.
