### ISSUE TITLE
An error "Can't parse this RSpec file. Please check errors." occurs when saving a spec file or switching the editor pane between files

### ISSUE THREAD

**Issue by sibevin** [Jacob84/rspec-tree-runner#21]
When I save a spec file or switch editor between files, it sometimes shows "Can't parse this RSpec file. Please check errors.". 

screen captures:

* Save file:

![save_file](https://cloud.githubusercontent.com/assets/2861357/21798393/1e17e0ee-d74f-11e6-8113-fe82ed631640.gif)

* Switch editor between files:

![switching_files](https://cloud.githubusercontent.com/assets/2861357/21798394/2265a2bc-d74f-11e6-9199-4edab0afb99b.gif)

the exception I catch at tree-builder.js:
```
"SyntaxError: Unexpected token { in JSON at position 604
    at Object.parse (native)
    at AstParser.parse (/Users/wangkaito/.atom/packages/rspec-tree-runner/lib/ast-parser.js:9:27)
    at TreeBuilder.buildFromStandardOutput (/Users/wangkaito/.atom/packages/rspec-tree-runner/lib/tree-builder.js:14:33)
    at RSpecAnalyzerCommand.<anonymous> (/Users/wangkaito/.atom/packages/rspec-tree-runner/lib/plugin-state-store.js:119:36)
    at emitOne (events.js:96:13)
    at RSpecAnalyzerCommand.emit (events.js:188:7)
    at RSpecAnalyzerCommand.parseData (/Users/wangkaito/.atom/packages/rspec-tree-runner/lib/rspec-analyzer-command.js:31:8)
    at TerminalCommandRunner.<anonymous> (/Users/wangkaito/.atom/packages/rspec-tree-runner/lib/rspec-analyzer-command.js:14:60)
    at emitOne (events.js:96:13)
    at TerminalCommandRunner.emit (events.js:188:7)
    at TerminalCommandRunner.onClose (/Users/wangkaito/.atom/packages/rspec-tree-runner/lib/terminal-command-runner.js:42:8)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)"
```

related versions I use:
```
rspec-tree-runner 1.0.4
atom 1.12.7

ruby 2.3.3
rspec-core 3.5.4
rspec-expectations 3.5.0
rspec-mocks 3.5.0
rspec-rails 3.5.2
rspec-support 3.5.0
```

**Comment by jacobmendoza** [comment]
The version 1.1.1 that has been just uploaded should fix this issue. 

@sibevin, if you find some time to test if now works for you, I'll be very grateful.
