### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by mvasin** [Jacob84/rspec-tree-runner#22]
[Enter steps to reproduce:]

Just installed the package and pressed Ctrl+Alt+l.

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [rspec-tree-runner](https://github.com/jacobmendoza/rspec-tree-runner) package 1.0.4

### Stack Trace

Uncaught TypeError: Cannot read property 'style' of null

```
At /Users/mvasin/.atom/packages/rspec-tree-runner/lib/index.js:83

TypeError: Cannot read property 'style' of null
    at Object.resizeSubContainer (/packages/rspec-tree-runner/lib/index.js:83:42)
    at Object.toggle (/packages/rspec-tree-runner/lib/index.js:57:8)
    at /packages/rspec-tree-runner/lib/index.js:32:79)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -6:07.0 tree-view:move (span.name.icon.test-ruby-icon.medium-red)
     -6:04.3.0 core:move-left (input.hidden-input)
     -6:03.3.0 core:confirm (input.hidden-input)
     -5:59.1.0 tree-view:move (span.name.icon.test-ruby-icon.medium-red)
     -5:56.9.0 core:move-right (input.hidden-input)
  3x -5:56.6.0 core:backspace (input.hidden-input)
     -5:54.5.0 core:confirm (input.hidden-input)
     -5:49.9.0 tree-view:move (span.name.icon.ruby-icon.medium-red)
     -5:46.5.0 core:confirm (input.hidden-input)
     -5:01.2.0 core:backspace (input.hidden-input)
     -4:58.5.0 core:save (input.hidden-input)
     -4:52.9.0 settings-view:open (input.hidden-input)
     -0:44 core:paste (input.hidden-input)
     -0:43.5.0 core:confirm (input.hidden-input)
     -0:11.1.0 core:copy (div.package-detail.panels-item)
     -0:09.1.0 rspec-tree-runner:toggle (div.package-detail.panels-item)
```

### Non-Core Packages

```
ansible-vault 0.6.3 
atom-beautify 0.30.3 
atom-erb 0.2.0 
atom-formatter-jsbeautify 1.1.2 
atom-jinja2 0.6.0 
auto-indent 0.5.0 
busy-signal 1.4.3 
compare-files 0.8.0 
cucumber 0.6.0 
devmind-beautifier 1.1.0 
file-icons 2.1.8 
indent-guide-improved 1.4.12 
intentions 1.1.2 
language-ansible 0.2.1 
language-docker 1.1.8 
language-gitignore 0.3.0 
language-haml 0.25.0 
language-htaccess 0.1.1 
language-ini 1.19.0 
language-log 1.8.0 
language-nginx 0.8.0 
language-pug 0.0.21 
language-rspec 0.6.2 
language-slim 0.5.0 
language-systemd 0.1.1 
linter 2.2.0 
linter-ansible-linting 1.3.0 
linter-ansible-syntax 1.2.0 
linter-csslint 1.3.4 
linter-erb 1.1.0 
linter-js-yaml 1.2.7 
linter-php 1.3.2 
linter-phpcs 1.6.7 
linter-rubocop 2.1.1 
linter-sass-lint 1.7.4 
linter-scss-lint 3.1.0 
linter-slim 1.0.0 
linter-ui-default 1.6.2 
minimap 4.28.2 
open-in-browser 0.5.2 
php-cs-fixer 4.1.0 
php-fmt 0.1.2 
rspec 0.3.2 
rspec-tree-runner 1.0.4 
tabs-to-spaces 1.0.3 
todo 0.6.0 
todo-show 1.11.0 
tree-view-git-status 1.4.0 
wordpress-dictionary 4.4.0 
```

**Comment by yashdoshi89** [comment]
I am also getting the same error
