### ISSUE TITLE
failed to activate package - fs is not defined

### ISSUE THREAD

**Issue by francescob** [Jacob84/rspec-tree-runner#3]
this is the error i'm getting when trying to run the package:

**Atom Version**: 0.205.0
**System**: Mac OS X 10.10.3
**Thrown From**: [rspec-tree-runner](https://github.com/Jacob84/rspec-tree-runner) package, v0.2.0
### Stack Trace

Failed to activate the rspec-tree-runner package

```
At fs is not defined

ReferenceError: fs is not defined
  at new RailsRSpecFinder (/Users/francesco/.atom/packages/rspec-tree-runner/lib/rails-rspec-finder.coffee:17:66)
  at new PluginState (/Users/francesco/.atom/packages/rspec-tree-runner/lib/plugin-state.coffee:10:22)
  at RSpecTreeView.module.exports.RSpecTreeView.initialize (/Users/francesco/.atom/packages/rspec-tree-runner/lib/rspec-tree-view.coffee:37:21)
  at RSpecTreeView.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new RSpecTreeView (/Users/francesco/.atom/packages/rspec-tree-runner/lib/rspec-tree-view.coffee:11:3)
  at Object.module.exports.getView (/Users/francesco/.atom/packages/rspec-tree-runner/lib/rspec-tree-runner.coffee:62:19)
  at Object.module.exports.activate (/Users/francesco/.atom/packages/rspec-tree-runner/lib/rspec-tree-runner.coffee:38:18)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:238:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:770:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:219:20)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```
### Commands

```
  2x -0:35.2.0 project-manager:toggle (atom-text-editor.editor)
     -0:30 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:26.3.0 pane:reopen-closed-item (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:11.9.0 ruby-test:toggle (atom-text-editor.editor.is-focused)
     -0:08.5.0 core:close (atom-text-editor.editor.is-focused)
     -0:05.4.0 rspec-tree-runner:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      "tags"
    ],
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "autoflow",
      "exception-reporting",
      "feedback",
      "image-view",
      "language-c",
      "language-gfm",
      "language-go",
      "language-objective-c",
      "markdown-preview",
      "metrics",
      "open-on-github",
      "package-generator",
      "policeman",
      "policeman-rubocop",
      "autocomplete",
      "keybinding-resolver",
      "language-java",
      "language-make",
      "language-toml",
      "styleguide",
      "welcome",
      "wrap-guide",
      "linter-scss-lint",
      "linter-rubocop",
      "archive-view",
      "symbols-view",
      "atom-lint",
      "toolbar",
      "toolbar-main",
      "log-console",
      "autocomplete-snippets",
      "atomatigit",
      "isearch",
      "smart-cutcopypaste",
      "related-files",
      "rsense",
      "language-mustache",
      "dev-live-reload",
      "language-clojure",
      "autosave",
      "sublime-tabs",
      "git-go",
      "atom-ctags",
      "synced-sidebar",
      "linter-haml",
      "language-csharp",
      "autocomplete-atom-api",
      "themed-settings"
    ],
    "projectHome": "/Users/francesco/projects",
    "audioBeep": false
  },
  "rspec-tree-runner": {}
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.3.0
autoclose-html, v0.17.0
autocomplete-paths, v1.0.2
color-picker, v2.0.4
compare-files, v0.4.1
csslint, v1.1.3
file-icons, v1.5.7
filetype-color, v0.1.4
git-log, v0.4.1
git-tab-status, v1.9.2
gutter-shadow, v0.4.3
jshint, v1.3.7
language-apache, v1.3.0
language-haml, v0.21.0
language-log, v0.4.0
language-rspec, v0.3.0
linter, v0.12.6
linter-coffeelint, v0.3.1
linter-csslint, v0.0.13
linter-erb, v0.1.1
linter-jshint, v0.1.6
linter-ruby, v0.1.6
notifications, v0.50.0
project-manager, v1.15.7
rails-i18n, v0.1.1
regex-railroad-diagram, v0.7.4
rspec-tree-runner, v0.2.0
ruby-block, v0.3.3
ruby-test, v0.9.11
space-tab, v0.4.1
symbols-tree-view, v0.9.3

# Dev
No dev packages
```

**Comment by jacobmendoza** [comment]
Hi,

Thanks a lot for reporting the error!. A detail has surprised me, you seem to have the version 0.2.0 of the plugin while the last version is 0.1.1. I had problems uploading the first version which contained different version numbers. Seems likely to me that you have a completely outdated version of the plugin.

Could you please uninstall the plugin and then reinstall again?

Thanks for your help.

**Comment by francescob** [comment]
Thanks, that solved this problem, now i have version 0.1.1
Still i'm not able to run my specs, but it's a problem i'm having both with your package and the rspec one:

WARNING: Unable to find ~/.rspec because the HOME environment variable is not set. Called from /usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.3/exe/rspec:4:in `<top (required)>'

any idea what this maybe?

**Comment by jacobmendoza** [comment]
Glad to hear that it worked. It seems that RSpec runner is not able to find your global config file. I know that probably I won't help very much, but have you tried to uninstall/install again?

http://rspec.info/documentation/3.2/rspec-core/

gem install rspec
gem install rspec-core
rspec --help

Let me know if this improves something.

**Comment by francescob** [comment]
Unfortunately that didn't help. The strange thing is that rspec it's working both from zsh (that i normally use) and bash, which from my understanding it's what atom uses. I posted the issue on the atom-rspec package as well, i hope they'll have a solution
Thanks for your time

**Comment by jacobmendoza** [comment]
Hi @francescob!,

Did you make any progress on that?. Any new information about what was happening?.

Thanks! :)

**Comment by francescob** [comment]
hi sorry for the late answer, i just found out that it works if i open atom from the terminal, but not from the icon on dock.

**Comment by jacobmendoza** [comment]
Great!,

Thanks a lot for your feedback! :)
