### ISSUE TITLE
Uncaught SyntaxError: Unexpected token b

### ISSUE THREAD

**Issue by dennis-best** [Jacob84/rspec-tree-runner#9]
Trying to run an rspec from a controller

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [rspec-tree-runner](https://github.com/jacobmendoza/rspec-tree-runner) package, v0.1.2
### Stack Trace

Uncaught SyntaxError: Unexpected token b

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2FUsers%2Fdennis.best%2FSites%2Forc%22%7D%5D%2C%22bootstrapScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%221.0.0%22%2C%22shellLoadTime%22%3A214%2C%22initialPaths%22%3A%5B%22%2FUsers%2Fdennis.best%2FSites%2Forc%22%5D%7D:1

SyntaxError: Unexpected token b
  at Object.parse (native)
  at RSpecLauncherCommand.module.exports.RSpecLauncherCommand.parseRSpecResult (/Users/dennis.best/.atom/packages/rspec-tree-runner/lib/rspec-launcher-command.coffee:25:57)
  at /Users/dennis.best/.atom/packages/rspec-tree-runner/lib/rspec-launcher-command.coffee:17:54
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TerminalCommandRunner.module.exports.TerminalCommandRunner.onClose (/Users/dennis.best/.atom/packages/rspec-tree-runner/lib/terminal-command-runner.coffee:47:14)
  at ChildProcess.<anonymous> (/Users/dennis.best/.atom/packages/rspec-tree-runner/lib/terminal-command-runner.coffee:1:1)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at maybeClose (child_process.js:997:16)
  at Socket.<anonymous> (child_process.js:1166:11)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```
### Commands

```
     -0:07.5.0 rspec-tree-runner:toggle (input.hidden-input)
     -0:02.4.0 rspec-tree-runner:run-tests (input.hidden-input)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".hg",
      ".svn",
      ".DS_Store",
      "Thumbs.db",
      "/public/*.*",
      ".keep"
    ],
    "disabledPackages": [
      "background-tips",
      "recent-files",
      "color",
      "color-gutter",
      "csscomb",
      "ruby-slim",
      "preview-tabs",
      "tab-switcher",
      "zentabs",
      "git-tab-status",
      "syntax-tree",
      "sassbeautify",
      "web-view",
      "atom-csscomb",
      "deprecation-cop",
      "exception-reporting",
      "tabs",
      "metrics",
      "multiple-cursors-clipboard",
      "open-recent",
      "language-hyperlink",
      "symbols-view",
      "ios",
      "autoflow",
      "autocomplete-snippets",
      "git-diff-popup",
      "git-diff-details",
      "tree-view",
      "file-icons",
      "devdocs",
      "snippets",
      "welcome",
      "autocomplete",
      "Atom-Syntax-highlighting-for-Sass",
      "go-to-view",
      "css-snippets",
      "language-css-plus",
      "linter-scss-lint",
      "merge-conflicts",
      "git-blame",
      "tree-view",
      "sublime-tabs",
      "ask-stack",
      "rails-rspec",
      "ruby-quick-test",
      "ruby-test"
    ],
    "themes": [
      "atom-light-ui",
      "twilight-syntax-spacegray-eighties"
    ],
    "projectHome": "/Users/dennisbest/Sites"
  },
  "rspec-tree-runner": {
    "rspecPathCommand": "bundle exec rspec"
  }
}
```
### Installed Packages

``` coffee
# User
Sass-Syntax-Highlight, v0.1.1
Sublime-Style-Column-Selection, v1.3.0
aligner-ruby, v1.4.0
aligner-scss, v1.0.1
atom-beautify, vundefined
auto-reveal-in-sidebar, v0.5.0
autosave-plus, v0.5.2
browser-plus, v0.0.23
color-picker, v2.0.9
javascript-snippets, v1.0.0
language-SCSS, v0.4.0
language-slim, v0.4.0
minimap, v4.10.2
pane-split-moves-tab, v0.0.1
pigments, v0.8.2
rspec-snippets, v0.4.0
rspec-tree-runner, v0.1.2
spec-maker, v0.4.0
spec-tree-view, v0.1.0
symbols-tree-view, v0.9.3
tree-view-open-files, v0.2.4
twilight-syntax-spacegray-eighties, v0.3.0

# Dev
No dev packages
```

**Comment by jacobmendoza** [comment]
Hi @dennis-best!,

I'd say this is happening because the package can't interpret the RSpec terminal runner output. Something unexpected is going on (obviously the error should be communicated better).

The package does two things when running a test file (ctrl+alt+x), changing to the project directory and then running RSpec to get the results (in JSON format). You can see these steps logged if activate the  developer tools (View -> Developer -> Toggle Developer Tools). 

Please, can you run RSpec inside your project and post here the relevant part of the result?. Should be similar to:

Open a terminal
cd project_directoy
rspec --format=json spec/file_that_failed_spec.rb

Thank you very much!

**Comment by dennis-best** [comment]
I replied here accidentally/on-purpose: https://github.com/jacobmendoza/rspec-tree-runner/issues/4 (I think they may be related?)

**Comment by jacobmendoza** [comment]
Hi @dennis-best,

I'm going to close this issue and concentrate efforts on #4. 

Thanks :)
